In [63]:
%matplotlib inline
import emcee
import numpy as np
from matplotlib import pyplot as plt
import pandas as pd

In [6]:
def ln_prob(param): return -param[0]*param[1]
num_steps = 10
num_walkers = 10
ndim = 2
pos = [np.random.normal(loc=0,scale=1,size=2)
       for _ in range(num_walkers)]

es = emcee.EnsembleSampler(num_walkers,
                           ndim,
                           ln_prob)
yo = es.run_mcmc(pos,num_steps)

In [145]:
np.mean([-np.inf,np.inf])

/Users/harmsm/miniconda3/lib/python3.12/site-packages/numpy/core/_methods.py:118: RuntimeWarning: invalid value encountered in reduce
  ret = umr_sum(arr, axis, dtype, out, keepdims, where=where)


nan

In [61]:
np.random.random(10)

array([0.47628129, 0.96412469, 0.24411467, 0.5481956 , 0.32095011,
       0.52541791, 0.63221125, 0.48021056, 0.46275819, 0.73930419])

In [148]:
def _sample_gaussian(prior_mean,
                     prior_std,
                     lower_bound,
                     upper_bound,
                     num_walkers):
    
    # generate a huge number of possible priors 
    gaussian_priors = np.random.normal(loc=prior_mean,
                                       scale=prior_std,
                                       size=num_walkers*1000)
    
    # Grab only those priors that are within the bounds
    good_mask = np.logical_and(gaussian_priors > lower_bound,
                               gaussian_priors < upper_bound)
    good_priors = gaussian_priors[good_mask]
    
    # If we have enough good priors, keep them. If we have only a few
    # good priors, it means the bounds have sliced out a ridiculously
    # tiny chunk of the distribution. Approximate the walkers as 
    # a uniform sample from that distribution. 
    if len(good_priors) >= num_walkers:
        return good_priors[:num_walkers]

    return None

def _sample_uniform(lower_bound,
                    upper_bound,
                    num_walkers,
                    infinity_proxy):

    # Slice down infinite bounds to largish numbers
    if np.isinf(lower_bound): 
        lower_bound = -infinity_proxy
    if np.isinf(upper_bound):
        upper_bound = infinity_proxy

    # If only one walker, put at the mean of the bounds
    if num_walkers == 1:
        return [np.mean([lower_bound,upper_bound])]

    # If the upper and lower bounds have the same sign, make a uniform
    # span between them (log steps). For example, 1e-9 to 1e-6 with four
    # walkers would yield 1e-9, 1e-8, 1e-7, 1e-6
    if upper_bound*lower_bound > 0:
        
        steps = np.exp(np.arange(num_walkers))
        steps = (steps - np.min(steps))/(np.max(steps) - np.min(steps))
        walkers = steps*(upper_bound - lower_bound) + lower_bound
        np.random.shuffle(walkers)
        
        return walkers

    # If the upper and lower bounds have different signs, make uniform
    # spans from 0 to upper and 0 to lower, weighted by how much of the
    # the span is above and below. 
    
    # Figure out fraction of uniform distribution below zero
    lower_mag = np.abs(lower_bound)
    upper_mag = np.abs(upper_bound)
    fx_lower = lower_mag/(lower_mag + upper_mag)

    # Figure out how many walkers to place above and below zero
    num_below = int(np.round(fx_lower*num_walkers,0))

    # Make sure we have at least one above and one below
    if num_below == 0: 
        num_below = 1
    if num_below == num_walkers:
        num_below = num_walkers - 1
    num_above = num_walkers - num_below

    # Create steps from 0 to upper_bound
    steps = np.exp(np.arange(num_above))
    steps = (steps - np.min(steps))/(np.max(steps) - np.min(steps))
    above_walkers = list(steps*upper_bound)

    # Create steps from 0 to lower_bound
    steps = np.exp(np.arange(num_below))
    steps = (steps - np.min(steps))/(np.max(steps) - np.min(steps))
    below_walkers = list(steps*lower_bound)

    # Combine all steps
    above_walkers.extend(below_walkers)
    walkers = np.array(above_walkers)

    # Shuffle randomly
    np.random.shuffle(walkers)

    return walkers


def _create_walkers(param_df,
                    num_walkers,
                    infinity_proxy=1e9):

    walker_list = []

    # Go through each parameter one-by-one
    for p in param_df.index:
        
        # Skip fixed parameters
        if param_df.loc[p,"fixed"]:
            continue

        # Get prior mean, std, and bounds
        guess = param_df.loc[p,"guess"]
        prior_mean = param_df.loc[p,"prior_mean"]
        prior_std = param_df.loc[p,"prior_std"]
        lower_bound = param_df.loc[p,"lower_bound"]
        upper_bound = param_df.loc[p,"upper_bound"]

        # If gaussian prior, try to do that first. 
        if not np.isnan(prior_mean):

            gaussian_priors = _sample_gaussian(prior_mean,
                                               prior_std,
                                               lower_bound,
                                               upper_bound,
                                               num_walkers)
            if gaussian_priors is not None:
                walker_list.append(gaussian_priors)
                continue

        # If we get here, gaussian priors were not given or did not work.
        uniform_priors = _sample_uniform(lower_bound,
                                         upper_bound,
                                         num_walkers,
                                         infinity_proxy)
        walker_list.append(uniform_priors)
        
    walkers = np.array(walker_list).T

    return walkers


param_df = pd.DataFrame({"name":["a","b"],
                        "guess":[1,2],
                        "fixed":[False,False],
                        "prior_mean":[np.nan,np.nan],
                        "prior_std":[2,np.nan],
                        "lower_bound":[-0.001,-np.inf],
                        "upper_bound":[0.001,np.inf]})

s = _create_walkers(param_df=param_df,
                num_walkers=10)
s

array([[-1.19202922e-04,  3.20586033e+07],
       [-0.00000000e+00,  1.19202922e+08],
       [ 0.00000000e+00,  3.56085740e+08],
       [-3.20586033e-05, -1.19202922e+08],
       [-3.56085740e-04,  0.00000000e+00],
       [ 1.00000000e-03, -3.20586033e+07],
       [-1.00000000e-03, -3.56085740e+08],
       [ 3.20586033e-05, -1.00000000e+09],
       [ 3.56085740e-04, -0.00000000e+00],
       [ 1.19202922e-04,  1.00000000e+09]])

In [131]:
np.log(10)
np.log(0.001)

-6.907755278982137

In [46]:
prior_dist = stats.sampling.FastGeneratorInversion(rv)
x = prior_dist.rvs((10,2))
means = np.array([0,1])
stds = np.array([10,1])

In [50]:
(x - means)/stds

array([[-0.00309253, -0.65680484],
       [-0.10013265, -2.06772866],
       [-0.01153172, -0.97799837],
       [ 0.29657577, -0.38081001],
       [-0.06001777,  0.47087776],
       [-0.03209133, -2.95918773],
       [ 0.06411045, -1.43260952],
       [-0.09383089, -0.040393  ],
       [-0.03906135, -1.07416001],
       [ 0.06609788, -1.31870454]])